blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    #post views
    #path('', views.post_list, name='post_list'),


    path('<int:year>/<int:month>/<int:day>/<slug:post>/'
             , views.post_detail, name='post_detail'),
    
    path('', views.PostListView.as_view(), name='post_list'),
    path('<int:post_id>/share/', views.post_share, name='post_share'),
    

]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog'))
]

urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    #post views
    #path('', views.post_list, name='post_list'),


    path('<int:year>/<int:month>/<int:day>/<slug:post>/'
             , views.post_detail, name='post_detail'),
    
    path('', views.PostListView.as_view(), name='post_list')
    

]

blog/models.py
from django.db import models

# Create your models here.
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse

class PublishedManager(models.Manager):
    def get_queryset(self):
        #super gives this class access to the proceeding parent method 
        # in this case, get_queryset
        return super().get_queryset().filter(status='published')

#Post model
class Post(models.Model):
    objects=models.Manager()
    published = PublishedManager()
    STATUS_CHOICES = (
        ('draft', 'DRAFT'),
        ('published', 'Published'),
    )

    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, 
                            unique_for_date='publish')

    author = models.ForeignKey(User, 
                                on_delete=models.CASCADE,
                                 related_name='blog_posts')
    body = models.TextField()

    publish = models.DateTimeField(default=timezone.now)

    #set the field to now when the object is first created
    created = models.DateTimeField(auto_now_add=True) 
    #Automatically set the field to now every time the object is saved
    updated = models.DateTimeField(auto_now=True) 

    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft')

    def get_absolute_url(self):
        return reverse(
            'blog:post_detail', args=[
                self.publish.year,
                self.publish.month,
                self.publish.day,
                self.slug
            ]
        )

    class Meta:
        ordering = ('-publish',)
        

    def __str__(self):
        return self.title

#Comment model
class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=50)
    email = models.EmailField()
    body = models.TextField()

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    #Order by date
    class Meta:
        ordering = ('created',)

    def __str__(self):
        return f'{self.name} on {self.post}'
    

models.py
from django.db import models

# Create your models here.
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse

class PublishedManager(models.Manager):
    def get_queryset(self):
        #super gives this class access to the proceeding parent method 
        # in this case, get_queryset
        return super().get_queryset().filter(status='published')

class Post(models.Model):
    objects=models.Manager()
    published = PublishedManager()
    STATUS_CHOICES = (
        ('draft', 'DRAFT'),
        ('published', 'Published'),
    )

    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, 
                            unique_for_date='publish')

    author = models.ForeignKey(User, 
                                on_delete=models.CASCADE,
                                 related_name='blog_posts')
    body = models.TextField()

    publish = models.DateTimeField(default=timezone.now)

    #set the field to now when the object is first created
    created = models.DateTimeField(auto_now_add=True) 
    #Automatically set the field to now every time the object is saved
    updated = models.DateTimeField(auto_now=True) 

    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft')

    def get_absolute_url(self):
        return reverse(
            'blog:post_detail', args=[
                self.publish.year,
                self.publish.month,
                self.publish.day,
                self.slug
            ]
        )

    class Meta:
        ordering = ('-publish',)
        

    def __str__(self):
        return self.title

blog/forms.py
from django import forms
from .models import *

class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=30)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(max_length=500, required=False, widget=forms.Textarea)

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name', 'email', 'body']

blog/views.py
from django.shortcuts import render, get_object_or_404

# Create your views here.
from .models import Post
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView

from .forms import EmailPostForm, CommentForm
from django.core.mail import send_mail

def post_list(request):
    
    object_list = Post.published.all()
    paginator = Paginator(object_list, 3) #3 posts in each page

    #Get the current page number
    page = request.GET.get('page')

    # Get the content of the page (posts)
    try:
        posts = paginator.page(page)
    
    #if page is not an integer, return first page
    except PageNotAnInteger:
        posts = paginator.page(1)
    
    #if page number is above the last page
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
   

    #pass the page number and retrieved objects to the template.
    return render(request, 'blog/post/list.html', {
                                            'posts': posts})

class PostListView(ListView):
    
    queryset = Post.published.all()
    context_object_name = 'posts'
    paginate_by = 3
    template_name = 'blog/post/list.html'
    


def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post,
                                slug=post,
                                status='published',
                                publish__year=year,
                                publish__month=month,
                                publish__day=day)
                        
    comments = post.comments.all().filter(active=True)
    new_comment = None

    if request.method == 'POST':
        #Get comment
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            #Commit,but dont save
            new_comment = comment_form.save(commit=False)

            #Assign the current post to the comment
            new_comment.post = post
            comment_form.save()
        
    else:
        comment_form = CommentForm()
            
    return render(request, 'blog/post/detail.html', {'post': post,
                                                'comments': comments,
                                                'comment_form': comment_form,
                                                'new_comment': new_comment})

#Shares post via mail
def post_share(request, post_id):
    post = get_object_or_404(Post, id=post_id, status='published')
    sent=False
    if request.method == 'POST':
        
        # Get form details
        form = EmailPostForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data

            #Create form messages
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = f'{cd["name"]} recommends you read {post.title}'
            message = f"Read {post.title} at {post_url} \n {cd['name']}'s comments: {cd['comments']}"
            send_mail(subject, message, 'atumasaake@gmail.com', [cd['to']])
            sent=True

    else:
        #present form
        form = EmailPostForm()
        
    return render(request, 'blog/post/share.html', {'post':post,
                                                'sent': sent,
                                                'form': form
                                                    })

blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset='UTF-8'>
        <meta name='viewport' content="width=device-width,
                            initial-scale=1, shrink-to-fit=no">
        <title>{% block title %}{% endblock %}</title>
        <link rel='stylesheet' href='{% static "css/blog.css" %}'>

        <!-- Not part of the book just personal-->
        <script src='{% static "js/pblog.js" %}'></script>
        <link rel='stylesheet' href='{% static "css/pblog.css" %}'>
        <!-- End of personal-->
        
    </head>

    <body>
        <!-- Not part of the book just personal-->
        <nav id='nav'>
            <div id='nav_home'>Blog</div>
            <ul id='hidelist'>
                <li>My blog</li>
                <li>This is my blog</li>
               
            </ul>
        </nav>
        <!-- End of personal-->

        <div id='section'>
            <div id='content'>
                {% block content %}
                {% endblock %}
            </div>

            <div id='sidebar'>
                <h2>My blog</h2>
            
                <p>This is my blog</p>
            </div>
        </div>


    </body>
</html>

blog/templates/blog/pagination.html
<div class='pagination'>
    <span class='step-links'>
        {% if page.has_previous %}
            <a href="?page={{ page.previous_page_number }}">Previous</a>
        {% endif %}
  

    <span class='current'>
        Page {{ page.number }} of {{ page.paginator.num_pages }}.
    </span>

    {% if page.has_next %}
         <a href="?page={{ page.next_page_number }}">
             Next
         </a>
    {% endif %}
</span>
</div>

blog/templates/blog/post/detail.html
{% extends 'blog/base.html' %}

{% block title %}{{ post.title }}{% endblock %}

{% block content %}
    
        <h1>{{ post.title }}</h1>

        <p class='date'>
            &#128197; {{ post.publish }} &#128100; by {{ post.author.username }}
        </p>
        <br/>
        {{ post.body | linebreaks }}
        <br/>
        <p>
            <a href="{% url 'blog:post_share' post.id %}">
                <button class='readMore'>Share this post</button>
            </a>
        </p>    


        {% if new_comment %}
            <h2>Your comment has been added</h2>
        {% else %}
        
            <h2>Add comment</h2>

            <form method='post'>
                {% csrf_token %}
                {{ comment_form.as_p }}
                <input type='submit' value='Add a comment'>
            </form>
        {% endif %}

        <br/>

        
        

        <nav id='commentInfo'>
            {% with comments.count as totalComments %}
        <h2>
            {{ totalComments }} comment{{ totalComments | pluralize }}
        </h2>
        <br/>
        {% endwith %}
        {% for comment in comments %}
            <div class='comment'>
                <p class='info'>
                    &#128100; Comment {{ forloop.counter }} by {{ comment.name }}
                    &#128197; {{ comment.created }}
                </p>
                <br/>
                {{ comment.body | linebreaks }}
            </div>

        {% empty %}
            <p> No comments yet</p>
        {% endfor %}
    </nav>

            <br/>


{% endblock %}

blog/templates/blog/post/list.html
{% extends 'blog/base.html' %}

{% block title %}My Blog{% endblock %}

{% block content %}
   

    {% for post in posts %}
        <h2>
            <a href='{{ post.get_absolute_url }}'>
                
                {{ post.title }}
            </a>
        </h2>
        <p class='date'>
            &#128197; {{ post.publish }} &#128100; by {{ post.author }}
        </p>

        {{ post.body | truncatewords:30 | linebreaks }}

        <br/>
        <a href='{{ post.get_absolute_url }}'>
            <button class='readMore'>Continue Reading</button>
        </a>
    
    {% endfor %}
    
        {% include "blog/pagination.html" with page=page_obj %}

{% endblock %}

blog/templates/blog/post/share.html
{% extends "blog/base.html" %}

{% block title %}Share a post {% endblock %}

{% block content %}

{% if sent %}

    <h2>Email sent successfully</h2>
    <p>"{{ post.title }}" was successfully sent to {{ form.cleaned_data.to }} </p>

{% else %}
    <h1>Share "{{ post.title }}" via mail</h1>
    <br>
    
    <form method='post' action='{% url "blog:post_share" post.id %}'>
    
        {% csrf_token %}
        {{ form.as_p }}
        <input type='submit' value='send a mail'>
   
    </form>
{% endif %}

{% endblock %}

templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset='UTF-8'>
        <meta name='viewport' content="width=device-width,
                            initial-scale=1, shrink-to-fit=no">
        <title>{% block title %}{% endblock %}</title>
        <link rel='stylesheet' href='{% static "css/blog.css" %}'>

        <!-- Not part of the book just personal-->
        <script src='{% static "js/pblog.js" %}'></script>
        <link rel='stylesheet' href='{% static "css/pblog.css" %}'>
        <!-- End of personal-->
        
    </head>

    <body>
        <!-- Not part of the book just personal-->
        <nav id='nav'>
            <div id='nav_home'>Blog</div>
            <ul id='hidelist'>
                <li>My blog</li>
                <li>This is my blog</li>
               
            </ul>
        </nav>
        <!-- End of personal-->

    
        <div id='content'>
            {% block content %}
            {% endblock %}
        </div>

        <div id='sidebar'>
            <h2>My blog</h2>
          
            <p>This is my blog</p>
        </div>

    </body>
</html>

templates/blog/post/list.html
{% extends 'blog/base.html' %}

{% block title %}My Blog{% endblock %}

{% block content %}
   

    {% for post in posts %}
        <h2>
            <a href='{{ post.get_absolute_url }}'>
                
                {{ post.title }}
            </a>
        </h2>
        <p class='date'>
            Published {{ post.publish }} by {{ post.author }}
        </p>

        {{ post.body | truncatewords:30 | linebreaks }}
    
    {% endfor %}
    
        {% include "blog/pagination.html" with page=posts %}

{% endblock %}